export const TOGGLE_FETCHING_MOVIES = "TOGGLE_FETCHING_MOVIES";
export const SET_MOVIES = "SET_MOVIES";
export const SET_MY_MOVIES = "SET_MY_MOVIES";
export const TOGGLE_UPDATED_MOVIES = "TOGGLE_UPDATED_MOVIES";
export const TOGGLE_SUBMITTING_MOVIE = "TOGGLE_SUBMITTING_MOVIE";
export const TOGGLE_UPDATED_MOVIE = "TOGGLE_UPDATED_MOVIE";
